name: CI
on:
  push:
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "pandas>=2.0,<3.0" "openpyxl>=3.1,<4.0"

      - name: Make sample input
        run: |
          python - << 'PY'
          import csv, os
          os.makedirs('Data', exist_ok=True)
          with open('Data/ci_sample.csv','w',newline='',encoding='utf-8') as f:
            w = csv.writer(f)
            w.writerow(['company_name','notes'])
            w.writerow(['Granite Works Limited','demo'])
            w.writerow(['GRANITE WORKS LTD','demo'])
            w.writerow(['Thistle Consulting L.L.P.','demo'])
            w.writerow(['Thistle Consulting LLP','demo'])
          PY

      - name: Run script
        run: |
          mkdir -p Output
          python company_intelligence.py --in Data/ci_sample.csv --out Output/ci_out.csv -v

      - name: Sanity check output
        run: |
          python - << 'PY'
          import csv
          with open('Output/ci_out.csv', encoding='utf-8') as f:
            rows = list(csv.reader(f))
          assert len(rows) >= 2, "No output rows?"
          print(f"OK: {len(rows)-1} unique rows")
          PY

      - name: Upload output (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ci-output
          path: Output/*
